spring:
  application:
    name: category-service
    config:
      import: optional:configserver:http://config-server:8888
  datasource:
    url: jdbc:mysql://category-db:3306/categoryDB?createDatabaseIfNotExist=true
    username: root
    password: mysqlroot
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: update
    show-sql: true

server:
  port: 8081